name: Tag

# master 브랜치에 push 할 때 동작
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 버전 정보 추출
      # commit message 에서 "x.x.x" 형식의 문자열을 추출하여 version 변수에 넣어준다.
      run: echo "VERSION=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
      id: extract_version_name
    - name: tag 생성
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ steps.extract_version_name.outputs.VERSION }}
